# === user-service ===
quarkus.http.port=8081
quarkus.application.name=user-service
# DataSource (à adapter par environnement)
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER:user_service}
quarkus.datasource.password=${DB_PASSWORD:user_service_pwd}
quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5433/users_db}
# Hibernate
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=false
# Log
quarkus.log.level=INFO
mp.jwt.verify.issuer=https://dev-cy8uphtpfx5bdclo.us.auth0.com/
mp.jwt.verify.publickey.location=https://dev-cy8uphtpfx5bdclo.us.auth0.com/.well-known/jwks.json
mp.jwt.verify.audiences=https://user-service.unigevents.com
#quarkus.http.auth.permission.authenticated.paths=/api/*
#quarkus.http.auth.permission.authenticated.policy=authenticated
mp.jwt.token.header=Authorization
smallrye.jwt.path.groups=https://unigevents.com/roles
quarkus.log.category."io.smallrye.jwt".level=DEBUG
quarkus.smallrye-openapi.path=/openapi