quarkus.http.port=8084
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${NOTIFICATION_DB_USER:notification_service}
quarkus.datasource.password=${NOTIFICATION_DB_PASSWORD:notification_service_pwd}
quarkus.datasource.jdbc.url=jdbc:postgresql://${NOTIFICATION_DB_HOST:localhost}:${NOTIFICATION_DB_PORT:5436}/${NOTIFICATION_DB_NAME:notifications_db}
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true
quarkus.smallrye-openapi.path=/openapi
