# === moderation-service ===
quarkus.http.port=8084
quarkus.application.name=moderation-service
# DataSource (à adapter par environnement)
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER:postgres}
quarkus.datasource.password=${DB_PASSWORD:postgres}
quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5432/unigevents_moderation}
# Hibernate
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=false
# Log
quarkus.log.level=INFO
quarkus.smallrye-openapi.path=/openapi