quarkus.http.port=8084
quarkus.application.name=moderation-service
# DataSource
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER:moderation_service}
quarkus.datasource.password=${DB_PASSWORD:moderation_service_pwd}
quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://moderation-db:5432/moderation_db}
# Hibernate
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=false
# Log
quarkus.log.level=INFO
quarkus.smallrye-openapi.path=/openapi
# Health + Prometheus metrics (auto-exposed at /q/health/{live,ready} and /q/metrics)
quarkus.micrometer.enabled=true
quarkus.micrometer.export.prometheus.enabled=true
quarkus.smallrye-health.root-path=/q/health
# Modération
openai.api.key=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
quarkus.rest-client.openai-moderation.url=https://api.openai.com
# Consommateur Kafka
mp.messaging.incoming.event-created.bootstrap.servers=kafka:9092
mp.messaging.incoming.event-created.connector=smallrye-kafka
mp.messaging.incoming.event-created.topic=event-created
mp.messaging.incoming.event-created.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.event-created.group.id=moderation-service
#%dev.mp.messaging.incoming.event-created.bootstrap.servers=
%dev.kafka.bootstrap.servers=kafka:9092