apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: unigevents
  labels:
    app: user-service
    app.kubernetes.io/part-of: unigevents
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: user-service
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: user-service
          image: ghcr.io/machanier/pinfo-2026-team1/user-service:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8081
          env:
            - name: DB_URL
              value: jdbc:postgresql://user-db:5432/users_db
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: user-db-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-db-secret
                  key: password
          resources:
            requests:
              cpu: "100m"
              memory: "384Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 40
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 90
            periodSeconds: 15
