quarkus.http.port=8083
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${REGISTRATION_DB_USER:registration_service}
quarkus.datasource.password=${REGISTRATION_DB_PASSWORD:registration_service_pwd}
quarkus.datasource.jdbc.url=jdbc:postgresql://${REGISTRATION_DB_HOST:localhost}:${REGISTRATION_DB_PORT:5435}/${REGISTRATION_DB_NAME:registration_service_db}
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true
quarkus.smallrye-openapi.path=/openapi
