# === registration-service ===
quarkus.http.port=8086
quarkus.rest-client.event-service.url=http://event-service:8082
quarkus.rest-client.user-service.url=http://user-service:8081
quarkus.application.name=registration-service
# DataSource (à adapter par environnement)
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER:registration_service}
quarkus.datasource.password=${DB_PASSWORD:registration_service_pwd}
quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5435/registrations_db}
# Hibernate
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=false
# Log
quarkus.log.level=INFO
quarkus.smallrye-openapi.path=/openapi
# Health + Prometheus metrics (auto-exposed at /q/health/{live,ready} and /q/metrics)
quarkus.micrometer.enabled=true
quarkus.micrometer.export.prometheus.enabled=true
quarkus.smallrye-health.root-path=/q/health
mp.jwt.verify.issuer=https://dev-cy8uphtpfx5bdclo.us.auth0.com/
mp.jwt.verify.publickey.location=https://dev-cy8uphtpfx5bdclo.us.auth0.com/.well-known/jwks.json
mp.jwt.verify.audiences=https://user-service.unigevents.com
mp.jwt.token.header=Authorization
quarkus.log.category."io.smallrye.jwt".level=DEBUG
kafka.bootstrap.servers=kafka:9092
mp.messaging.outgoing.registration-confirmed.connector=smallrye-kafka
mp.messaging.outgoing.registration-confirmed.topic=registration.confirmed
mp.messaging.outgoing.registration-confirmed.value.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.registration-waitlisted.connector=smallrye-kafka
mp.messaging.outgoing.registration-waitlisted.topic=registration.waitlisted
mp.messaging.outgoing.registration-waitlisted.value.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.registration-cancelled.connector=smallrye-kafka
mp.messaging.outgoing.registration-cancelled.topic=registration.cancelled
mp.messaging.outgoing.registration-cancelled.value.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.registration-confirmed.bootstrap.servers=kafka:9092
mp.messaging.outgoing.registration-waitlisted.bootstrap.servers=kafka:9092
mp.messaging.outgoing.registration-cancelled.bootstrap.servers=kafka:9092
mp.messaging.incoming.event-cancelled.connector=smallrye-kafka
mp.messaging.incoming.event-cancelled.topic=event.cancelled
mp.messaging.incoming.event-cancelled.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.event-cancelled.group.id=registration-service
