apiVersion: v1
kind: Service
metadata:
  name: search-db
  namespace: unigevents
  labels:
    app: search-db
    app.kubernetes.io/part-of: unigevents
spec:
  clusterIP: None
  selector:
    app: search-db
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
