quarkus.http.port=8085
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${SEARCH_DB_USER:search_service}
quarkus.datasource.password=${SEARCH_DB_PASSWORD:search_service_pwd}
quarkus.datasource.jdbc.url=jdbc:postgresql://${SEARCH_DB_HOST:localhost}:${SEARCH_DB_PORT:5437}/${SEARCH_DB_NAME:search_service_db}
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true
quarkus.smallrye-openapi.path=/openapi
