# === event-service ===
quarkus.http.port=8082
quarkus.application.name=event-service
# DataSource (à adapter par environnement)
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER:event_service}
quarkus.datasource.password=${DB_PASSWORD:event_service_pwd}
quarkus.datasource.jdbc.url=jdbc:postgresql://${EVENT_DB_HOST:event-db}:${EVENT_DB_PORT:5432}/events_db
# Hibernate
quarkus.hibernate-orm.schema-management.strategy=update
quarkus.hibernate-orm.mapping.format.global=ignore
quarkus.hibernate-orm.log.sql=false
# Log
quarkus.log.level=INFO
quarkus.smallrye-openapi.path=/openapi